# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - run: npm install pm2@latest -g
    - run: npm install
    - run: pm2 delete api -f
      continue-on-error: true
    - run: npm run build
    - run: pm2 start dist/server.js --name api
